### ISSUE TITLE
Decoyfinder usage problem

### ISSUE THREAD

**Issue by jaminzzz** [cgoliver/rnamigos2#3]
Hello,
Awesome work! Could I ask how you use decoyfinder to generate decoy because I get a http error when using it with the default zinc settings.

Thanks!
Jamin

**Comment by cgoliver** [comment]
Hello @jaminzzz ! Thanks for using our tool :)

Can you please paste the command you used and the full output?

**Comment by jaminzzz** [comment]
Hi, @cgoliver ! Thank you for your super quick reply！
I use the windows version and it will report the following error:
![image](https://github.com/cgoliver/rnamigos2/assets/62273762/a7d921b2-a061-4e58-ad45-df850d8d8c8e)
I also found related issues https://github.com/URV-cheminformatics/DecoyFinder/issues/4

Could you tell me how you use it?
Thanks a lot！

**Comment by cgoliver** [comment]
Ah I see. That is an issue with decoyfinder so I can't really help. Looks like you are having trouble connecting to the server hosting the decoys (in this case ZINC). Perhaps the URL changed?

We provide a wrapper to decoy finder which you can find out how to use [here](https://github.com/cgoliver/rnamigos2/blob/master/REPRODUCE.md#generate-actives-and-decoys-list) through the command line. 

Let me know if I can help with anything else.

**Comment by jaminzzz** [comment]
Great, I'll check it out！！！🫡
